name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:

  deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install lib-ssl
      run: sudo apt install libssl-dev

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
